# Generated by Django 4.2.20 on 2025-05-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_session_id_cart_total_cart_total_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
