# Generated by Django 4.2.20 on 2025-05-03 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0003_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="session_id",
            field=models.CharField(max_length=244, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
