# Generated by Django 4.2.20 on 2025-05-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cart_session_id_alter_cart_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "game"), name="unique_game_in_cart_constraint"
            ),
        ),
    ]
