# Generated by Django 4.2.20 on 2025-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_rename_url_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="discount_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="game",
            name="release_year",
            field=models.IntegerField(),
        ),
    ]
